tiangolo/latest-changes

- Dockerfile
- app/__main__.py
- app/model.py
- app/requirements.txt
🐛 Small fixes so it runs correctly in Docker (at least)
> 🐛 Small fixes so it runs correctly in Docker

- app/__main__.py
- app/model.py
🐛 Fix Pydantic models from incorrect GitHub OpenAPI/JSON Schema
> 🐛 Fix Pydantic models from incorrect GitHub OpenAPI/JSON Schema

- .github/workflows/latest-changes.yml
♻️ Update PR GitHub Action event to use
> ♻️ Update PR GitHub Action event to use

- .github/workflows/latest-changes.yml
> 🔧 Add debugging tmate

- README.md
- app/__main__.py
> 🔊 Debug and debug again

- README.md
🍻 Keep debugging and developing through commits and branches because GitHub Actions
> 🍻 Keep debugging and developing through commits and branches because GitHub Actions

- app/__main__.py
✨ Try to git login as GitHub Actions
> ✨ Try to git login as GitHub Actions

- .github/workflows/latest-changes.yml
> 🚚 Move tmate to last step

- app/__main__.py
♻️ Try to git pull before pushing the changes
> ♻️ Try to git pull before pushing the changes

- app/__main__.py
> 👷 Trigger CI

- app/__main__.py
♻️ Update URLs to use in latest changes
> ♻️ Update URLs to use in latest changes

- README.md
> 📝 Update release notes URLs

- .github/workflows/latest-changes.yml
> 🔒 Try to secure tmate

- README.md
> ✏️ Fix incorrect URL

- .github/workflows/latest-changes.yml
🔒 Update tmate config for keys
> 🔒 Update tmate config for keys

- .github/workflows/latest-changes.yml
- README.md
> 🔧 Update tmate config keys

- README.md
🔥 Remove unnecessary note from latest changes
> 🔥 Remove unnecessary note from latest changes

- README.md
🔥 Remove unnecessary note from release notes
> 🔥 Remove unnecessary note from release notes

- app/__main__.py
- app/latest-changes.jinja2
- requirements.txt
✨ Add support for Jinja2 templates for changes notes
> ✨ Add support for Jinja2 templates for changes notes

- action.yml
- app/__main__.py
🔊 Add debugging logs and option
> 🔊 Add debugging logs and option

- action.yml
- app/__main__.py
♻️ Make GitHub token optional as it is not used in the current version
> ♻️ Make GitHub token optional as it is not used in the current version

- .github/workflows/latest-changes.yml
- action.yml
- app/__main__.py
🔊 Enable debug logs and format
> 🔊 Enable debug logs

- README.md
> 📝 Add usage docs

- action.yml
🐛 Fix default action config for template file
> 🐛 Fix default action config for template file

- README.md
📝 Add note about updating the PR title
> 📝 Add note about updating the PR title

- README.md
🐛 Fix basic example in README, include checkout step
> 🐛 Fix basic example in README, include checkout step

- .github/workflows/latest-changes.yml
- README.md
- app/__main__.py
🐛 Fix workflow dispatch, remove condition blocking it in workflow
> 🐛 Fix workflow dispatch, remove condition blocking it in workflow

- README.md
- app/__main__.py
- requirements.txt
📝 Add docs for running manually, with a workflow dispatch.
And cleanup main code, remove unneeded dependency `devtools`.
> 📝 Add docs for running manually, with a workflow dispatch

- app/__main__.py
✨ Check if the latest changes message was already added before adding it
> ✨ Check if the latest changes message was already added before adding it

- README.md
> 🔖 Release version 0.0.2

- action.yml
🐛 Fix default Jinja2 path in Action yaml
> 🐛 Fix default Jinja2 path in Action yaml

- README.md
📝 Add docs for using latest-changes with protected branches
> 📝 Add docs for using latest-changes with protected branches

- .github/workflows/docker-push.yml
🔥 Remove config pushing to custom branch for debugging
> 🔥 Remove config pushing to custom branch for debugging

- .github/FUNDING.yml
- .github/dependabot.yml
- .github/workflows/latest-changes.yml
👷 Update CI, Dependabot, funding
> 👷 Update CI, Dependabot, funding

- .github/workflows/docker-push.yml
👷 Do not push the slim branch for debugging
> 👷 Do not push the slim branch for debugging

- README.md
- latest_changes/main.py
- tests/test_generate_content.py
🐛 Fix handling multiple section headers
> 🐛 Fix handling multiple section headers

- latest_changes/main.py
✨ Add retries to handle race conditions
> ✨ Add retries to handle race conditions

- README.md
📝 Update README docs for token permissions
> 📝 Update README docs for token permissions

- latest_changes/main.py
🐛 Fix race condition with retries, when more than one latest-changes is running
> 🐛 Fix race condition with retries, when more than one latest-changes is running

- .github/workflows/docker-push.yml
- Dockerfile
- README.md
- base.dockerfile
♻️ Make using the native GitHub Action re-use the existing Docker image instead of building from scratch
> ♻️ Make using the native GitHub Action re-use the existing Docker image instead of building from scratch

- README.md
> 📝 Tweak and fix tag to use

- README.md
📝 Tweak docs with new label infra
> 📝 Tweak docs with new label infra
